spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb
    username: notes
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true